### ISSUE TITLE
Add the option of an indicator to show the filter is running successfully.

### ISSUE THREAD

**Issue by robgilbert101** [TheJollyBeardo/OBS_RTX_SuperResolution#3]
Hi 

Would it be possible to add a small indicator in the corner of the screen to show the rtx super resolution filter is being applied (similar to the way 'NIS' appears in the top left when using nVidia image scaling). Trying to apply the filter to an HDR 1440p source and not sure if it is being successful or not.

**Comment by Bemjo** [comment]
> Hi
> 
> Would it be possible to add a small indicator in the corner of the screen to show the rtx super resolution filter is being applied (similar to the way 'NIS' appears in the top left when using nVidia image scaling). Trying to apply the filter to an HDR 1440p source and not sure if it is being successful or not.

Hello!

1. I have pushed a new release that adds a status text on the super resolution filter window itself.

This text will either tell you explicitly that this plugin is enabled and working, or if there is a problem preventing it from functioning.

I understand how deceptive the results from this plugin can seem and make you question if it's doing anything, I added this prompt late last year for myself for exactly this reason.

2. I have no idea how this interacts with HDR content in OBS! I do not possess an HDR display to test HDR content with, and as such I don't have any HDR content and have not tested this with any.

Ideally this should produce, not using artifact reduction, the exact same image in terms of coloration. If you notice any difference in the color or capture results when enabling this plugin with HDR content, please feel free to file another issue!

3. The results produced from this plugin will not match those of a non-realtime AI upscaler like Topaz, and your results will vary depending on the content itself!

Anecdotally I have noticed a large variation in terms of results across different types of content (Live, Animated, CGI, etc) and it's quality (Low Resolutions, Highly Artifact-ed).

If you're having trouble SEEING the difference, I can recommend adding a scale/aspect ratio filter at the end of your filter chain, making it something like 5x-10x your source size and setting it's type to Point.

This will give you an unfiltered nearest-neighbor zoom on your source, and as you toggle the SuperResolution plugin you can see the effects of its upscaling.

You can also add another scale/aspect ratio in-place of SuperResolution, set its resolution to your expected output resolution that your selected scale would produce (ex, a 720p source scaled 1.5x is 1080p), and use that to see the difference between the various built-int filters that OBS uses and the results this plugin produces.

I have been meaning to make a small gallery to compare the various filters in OBS this way.

**Comment by Bemjo** [comment]
Closing as I believe the issue has been at least mostly solved, and there has been no feedback on this.

I would like to have more a more real-time notice when it detects an issue with your source/settings, instead of having to click off/on the filter entry or clicking the Verify Source button, but I have not been able to get OBS to update the properties UI of the filter, while it is being displayed, from external events.
